### PR TITLE
Updates for Silverstripe 5.x

### PR DESCRIPTION
**Pull request by scott-nz**
Includes Unit test changes for PHPUnit 9.6

Note: https://github.com/madmatt/silverstripe-encrypt-at-rest/pull/31 would need to be merged first to ensure proper Silverstripe 4 compatibility

### CODE REVIEW

**Comment by madmatt** [comment]
This looks good to me. It does mean that we are moving immediately from SS4 to SS5 compatibility which is fine but I suspect creating a `4` branch might be a good idea for a little while in case there are fixes required there.

I'm wanting to get GitHub Actions set up to run on all PRs etc to replace the in-project testing that was previously happening - @scott-nz if I gave you repo access would you be willing/able to set this up, or do you not have any time left for changes/updates?

Thanks!

**Comment by madmatt** [comment]
FYI this will resolve #29.

**Comment by Firesphere** [comment]
> This looks good to me. It does mean that we are moving immediately from SS4 to SS5 compatibility which is fine but I suspect creating a 4 branch might be a good idea for a little while in case there are fixes required there.

From what I can see, these changes do not break SS4, so there's no need to go to 5 immediately?

Haven't extensively tested though.

**Comment by madmatt** [comment]
In that case, maybe a simple `^4|^5` in the composer.json might be okay, with a matching Readme update? I haven't tested this on SS4 yet so can't confirm right away - perhaps you might know @scott-nz?

**Comment by edwilde** [comment]
Unless anyone has any objections, I will merge and release this as `v2.0.0` on Friday 13 😬 September

**Comment by madmatt** [comment]
👻 Thanks Ed!

**Pull request merged**
